name: CI_flow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: log date
        run: date -Iminutes > /tmp/log.txt
      - name: log submitters
        run: echo "Alon Hartanu" >> /tmp/log.txt
      - name: checkout
        uses: actions/checkout@v3
      - name: create ninja key file
        run: echo ${{ secrets.NINJA_API_KEY }} > ninja_api_key
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and export
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: meals_and_dishes:latest
          outputs: type=docker,dest=/tmp/meals_and_dishes.tar
      - name:  log failed build
        if: failure()
        run: echo "image not able to be built" >> /tmp/log.txt
      - name: log successful build
        run: echo "image successfully built" >> /tmp/log.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: from_build
          path: /tmp/meals_and_dishes.tar
      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: .
          path: /tmp/log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: load docker image
        run: docker load --input from_build/meals_and_dishes.tar
      - name: install tests requirements
        run: pip install -r tests/requirements_tests.txt
      - name: run docker image
        run: docker run --rm -d --name meals_and_dishes meals_and_dishes:latest
      - name: log container up
        run: echo "Container up and running" >> ./log.txt
      - name: run tests
        run: pytest -v tests/assignment3_tests.py 1>assn3_test_results.txt 2>&1
      - name: stop container
        run: docker stop meals_and_dishes:latest
      - name: log test succeed
        run: echo "tests succeeded" >> ./log.txt
      - name: log test failed
        if: failure()
        run: echo "tests failed" >> ./log.txt
      - name: Upload test log
        uses: actions/upload-artifact@v3
        with:
          name: .
          path: assn3_test_results.txt

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: load docker image
        run: docker load --input from_build/meals_and_dishes.tar
      - name: install tests requirements
        run: pip install -r tests/requirements_tests.txt
      - name: run docker image
        run: docker run --rm -d --name meals_and_dishes meals_and_dishes:latest
      - name: log container up
        run: echo "Container up and running" >> ./log.txt
      - name: run queries
        run: python tests/query_job.py
      - name: upload test results
        uses: actions/upload-artifact@v3
        with:
            name: query_results.txt
            path: response.txt
      - name: Upload query log
        uses: actions/upload-artifact@v3
        with:
          name: .
          path: query_response.txt

